### ISSUE TITLE
Code snippets display differently in Shady DOM vs Shadow DOM

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-sass-doc#11]
The code snippet in Shady DOM has syntax highlighting, but it incorrectly expands the code (e.g. px-icon) and shows everything within the components:

![screen shot 2017-07-31 at 10 29 37 am](https://user-images.githubusercontent.com/9092541/28790406-c227bbc8-75dd-11e7-8402-7723d0c971ae.png)

The code snippet in Shadow DOM shows the component as intended (i.e. doesn't show the innards of px-icon), but it does not have syntax highlighting:

![screen shot 2017-07-31 at 10 29 56 am](https://user-images.githubusercontent.com/9092541/28790405-c22128b2-75dd-11e7-8a09-b01ada41e229.png)

**Comment by randyaskin** [comment]
I added to the regex to strip px-icon out of both the actionable-design and button-design demos. Also updated the logic to re-strip the "style-scope px-whatever-demo" since we gave them all unique names last Friday. See 8348a39ffdff9a9e2eb647e951717c4e7f2ee054

I'm not sure why the marked-element syntax highlighting doesn't work in shadow dom mode, considering it's a Google component. I tried updating to v2+ of marked-element but that only broke the gray background and didn't help with the highlighting, so I reverted back to v1.
